namespace DarkBestiary
{
    public enum KeyType
    {
        Move,
        Stop,
        Skill1,
        Skill2,
        Skill3,
        Skill4,
        Skill5,
        Skill6,
        Skill7,
        Skill8,
        Skill9,
        Skill10,
        SwapWeapon,
        ConsumablesBag,
        EndTurn,
        Equipment,
        Reliquary,
        Masteries,
        Attributes,
        Talents,
        Skills,
        Achievements,
        CombatLog,
        DamageMeter,
        Mailbox,
        Menu,
        IncreaseGameSpeed,
        DecreaseGameSpeed,
    }
}