namespace DarkBestiary.Items
{
    public enum AttachmentPoint
    {
        None,
        Auto,
        Origin,
        OverHead,
        Chest,
        Head,
        Mask,
        Hair,
        LeftHand,
        RightHand,
        LeftFist,
        RightFist,
        LeftFoot,
        RightFoot,
        GunBarrel,
        Shield,
        Belt,
        RightShoulder,
        LeftShoulder,
        Back,
        Special01,
        Special02,
        Special03,
    }
}