namespace DarkBestiary.Properties
{
    public enum PropertyType
    {
        None,

        AttackPower,
        SpellPower,
        Health,
        HealthRegeneration,
        Thorns,
        RangedWeaponExtraRange,
        MagicExtraRange,
        MaximumActionPoints,
        RageGeneration,
        CooldownReduction,

        CriticalHitChance,
        CriticalHitDamage,
        HealingCriticalChance,
        DamageReflection,
        Vampirism,
        Dodge,
        BlockChance,
        BlockAmount,

        MinionDamage,
        MinionHealth,
        ArmorPenetration,
        MagicPenetration,

        CrushingResistance,
        SlashingResistance,
        PiercingResistance,
        FireResistance,
        ColdResistance,
        HolyResistance,
        ShadowResistance,
        ArcaneResistance,
        PoisonResistance,
        LightningResistance,

        HealingIncrease,
        DamageIncrease,
        PhysicalDamageIncrease,
        MagicalDamageIncrease,
        MeleeDamageIncrease,
        RangedDamageIncrease,
        PiercingDamageIncrease,
        SlashingDamageIncrease,
        CrushingDamageIncrease,
        FireDamageIncrease,
        PoisonDamageIncrease,
        ColdDamageIncrease,
        ShadowDamageIncrease,
        HolyDamageIncrease,
        LightningDamageIncrease,
        ArcaneDamageIncrease,
        OffhandDamageIncrease,

        IncomingHealingIncrease,

        IncomingDamageReduction,
        IncomingMagicalDamageReduction,
        IncomingPhysicalDamageReduction,
        IncomingCrushingDamageReduction,
        IncomingSlashingDamageReduction,
        IncomingPiercingDamageReduction,
        IncomingFireDamageReduction,
        IncomingColdDamageReduction,
        IncomingHolyDamageReduction,
        IncomingShadowDamageReduction,
        IncomingArcaneDamageReduction,
        IncomingPoisonDamageReduction,
        IncomingLightningDamageReduction,

        Alchemy,
        Experience
    }
}